

INSERT INTO countries VALUES(1,'INDIA',91,'INR','ASIA');
INSERT INTO countries VALUES(2,'SOUTHKOREA',82,'KRW','ASIA');
INSERT INTO countries VALUES(3,'JAPAN',81,'YEN','ASIA');
INSERT INTO countries VALUES(4,'AUSTRALIA',61,'AUD','AUSTRALIA');
INSERT INTO countries VALUES(5,'BELGIUM',32,'EUR','EUROPE');
INSERT INTO countries VALUES(6,'CANADA',1,'CAD','NRTH AMER');
INSERT INTO countries VALUES(7,'DENMARK',45,'DKK','EUROPE');
INSERT INTO countries VALUES(8,'FRANCE',33,'EUR','EUROPE');
INSERT INTO countries VALUES(9,'GERMANY',49,'EUR','EUROPE');
INSERT INTO countries VALUES(10,'US',1,'USD','NRTH AMR');

SELECT * FROM countries;


