CREATE TABLE CUSTOMERS
(
CUSTOMER_ID INT AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(10),
PRICE INT,
PRODUCT VARCHAR(10),
QUANTITY INT,
PRIMARY KEY(CUSTOMER_ID)
);
INSERT INTO CUSTOMERS VALUES (1,'AMITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (2,'ARPITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (3,'ARUNITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (4,'AMRUTHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (5,'ANKITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (6,'ANWITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (7,'ASHWITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (8,'ARSHITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (9,'ASHWITHA',10000,'STATIONARY', 10);
INSERT INTO CUSTOMERS VALUES (10,'ASMITHA',10000,'STATIONARY', 10);

SELECT * FROM CUSTOMERS;
