CREATE TABLE TIMEZONE
(
TIMEZONE_ID INT AUTO_INCREMENT,
COUNTRY_ID INT,
TIME_ZONE  FLOAT,
PRIMARY KEY(TIMEZONE_ID),
FOREIGN KEY( COUNTRY_ID) REFERENCES countries(COUNTRY_ID)
);
INSERT INTO TIMEZONE VALUES(1,1,5.30);
INSERT INTO TIMEZONE VALUES(2,2,9.0);
INSERT INTO TIMEZONE VALUES(3,3,9.0);
INSERT INTO TIMEZONE VALUES(4,4,11.0);
INSERT INTO TIMEZONE VALUES(5,5,1.0);
INSERT INTO TIMEZONE VALUES(6,6,-5.0);
INSERT INTO TIMEZONE VALUES(7,7,1.0);
INSERT INTO TIMEZONE VALUES(8,8,1.0);
INSERT INTO TIMEZONE VALUES(9,9,1.0);
INSERT INTO TIMEZONE VALUES(10,10,5.0);

SELECT * FROM TIMEZONE;

#

SELECT T.TIME_ZONE,C.COUNTRY_NAME
FROM TIMEZONE AS T , COUNTRIES AS C
WHERE
T.COUNTRY_ID=C.COUNTRY_ID;

