CREATE TABLE MCA
(
ROLL_NO INT AUTO_INCREMENT,
UNI_ID VARCHAR(15),
COURSE_ID VARCHAR(15),
COLLEGE_ID INT,
FIRST_NAME VARCHAR(15),
LAST_NAME VARCHAR(15),
M_GENDER VARCHAR(8),
YEAR_OF_ADMISSION INT,
PRESENT_YEAR_IN INT,
PRIMARY KEY(ROLL_NO)
);

INSERT INTO MCA
VALUES
(1,123,'MCA','12','ANKITHA','NAYAK','F',2022,1);

INSERT INTO MCA
VALUES
(2,123,'MCA','2','ANKITH','NAYAK','M',2022,1);

INSERT INTO MCA
VALUES
(3,123,'MCA',3,'BHARATH','RAO','M',2020,2);

INSERT INTO MCA
VALUES
(4,123,'MCA',4,'BHARATHI','NAYAK','F',2021,2);

INSERT INTO MCA
VALUES
(5,123,'MCA',5,'SWATHI','ACHARYA','F',2021,1);

INSERT INTO MCA
VALUES
(6,123,'MCA',6,'KARTHIK','ACHARYA','M',2020,3);

INSERT INTO MCA
VALUES
(7,123,'MCA',7,'JEEZA','MENDONSA','F',2020,3);

INSERT INTO MCA
VALUES
(8,123,'MCA',8,'JOY','MENDONSA','M',2019,4);

INSERT INTO MCA
VALUES
(9,123,'MCA',9,'RAKSHITHA','SHETTY','F',2021,2);

INSERT INTO MCA
VALUES
(10,123,'MCA',10,'RAHUL','PRABHU','M',2022,1);

INSERT INTO MCA
VALUES
(11,123,'MCA',11,'SANJANA','NAYAK','F',2019,3);

INSERT INTO MCA
VALUES
(12,123,'MCA',12,'RAMYA','BHAT','F',2022,1);

INSERT INTO MCA
VALUES
(13,123,'MCA',13,'AKHIL','KAMATH','F',20,2);

INSERT INTO MCA
VALUES
(14,123,'MCA',14,'RUHI','PRABHU','F',2020,3);

INSERT INTO MCA
VALUES
(15,123,'MCA',15,'ROHAN','RAO','M',2018,4);


# REPORT
#**************************************************
# A)1. List of girl students in 3rd year of B.Pharm
#********************************************
 # MP= M.PHARM
 # MCA
 # BP= B.PHARM
 # M= MALE & F= FEMALE.

 
SELECT * FROM B_PHARM
WHERE (PRESENT_YEAR_IN=3 AND B_GENDER='F'AND COURSE_ID='BP');

# A)2.ALL GIRLS WHO ARE IN THIRD YEAR 

SELECT  M.COURSE_ID, M.FIRST_NAME, M.LAST_NAME, M.M_GENDER, M.PRESENT_YEAR_IN,B.FIRST_NAME,B.LAST_NAME,B.B_GENDER,B.COURSE_ID,P.FIRST_NAME, P.LAST_NAME, P.P_GENDER, P.COURSE_ID 
FROM
MCA AS M , B_PHARM AS B, M_PHARM AS P
WHERE 
(M.PRESENT_YEAR_IN=3 AND P.PRESENT_YEAR_IN=3 AND B.PRESENT_YEAR_IN=3) AND (M.M_GENDER='F') AND (P.P_GENDER='F') AND( B.B_GENDER='F');


SELECT DISTINCT  M.COURSE_ID, M.FIRST_NAME, M.LAST_NAME, M.M_GENDER, M.PRESENT_YEAR_IN,B.FIRST_NAME,B.LAST_NAME,B.B_GENDER,B.COURSE_ID
FROM
MCA AS M , B_PHARM AS B
WHERE 
(M.M_GENDER='F');

#********************************************
 # b) Names of all boys whose surname is "Rao"
 #********************************************
 # MP= M.PHARM
 # MCA
 # BP= B.PHARM
 # M= MALE & F= FEMALE.

 
 SELECT DISTINCT M.FIRST_NAME,M.LAST_NAME,M.M_GENDER,M.COURSE_ID,B.FIRST_NAME, B.LAST_NAME, B.B_GENDER, B.COURSE_ID , P.FIRST_NAME,P.LAST_NAME, P.P_GENDER, P.COURSE_ID
 FROM
 m_pharm AS P , b_pharm AS B , MCA AS M
 WHERE 
  (M.LAST_NAME='RAO' AND P.LAST_NAME='RAO' AND B.LAST_NAME='RAO') AND  (M.M_GENDER='M') AND (P.P_GENDER='M') AND( B.B_GENDER='M');
  

#********************************************
